---
title: "Forest Fire Exploration"
author: "w203 Teaching Team"
output: pdf_document
---

## Background

In some areas, forest fires are a major environmental concern, endangering human lives and causing substantial economic damage.  Your team has been hired by an agency that is developing an early warning system to identify particularly damaging forest fires. 


## Data

You are provided with the file **forestfires.csv**, containing measurements taken of recent fires in a Portuguese park.

As a proxy for how damaging a fire is, you should use the area variable, representing the region burned in hectares.

The dataset includes a number of meteorological variables.  Some of these come from the forest Fire Weather Index (FWI), a Canadian system for rating fire danger. These include Fine Fuel Moisture Code (FFMC),
Duff Moisture Code (DMC), Drought Code (DC), and Initial Spread Index (ISI).

The following codebook summarizes each variable:

   1. X - x-axis spatial coordinate within the Montesinho park map: 1 to 9
   2. Y - y-axis spatial coordinate within the Montesinho park map: 2 to 9
   3. month - month of the year: "jan" to "dec" 
   4. day - day of the week: "mon" to "sun"
   5. FFMC - FFMC index from the FWI system: 18.7 to 96.20
   6. DMC - DMC index from the FWI system: 1.1 to 291.3 
   7. DC - DC index from the FWI system: 7.9 to 860.6 
   8. ISI - ISI index from the FWI system: 0.0 to 56.10
   9. temp - temperature in Celsius degrees: 2.2 to 33.30
   10. RH - relative humidity in %: 15.0 to 100
   11. wind - wind speed in km/h: 0.40 to 9.40 
   12. rain - outside rain in mm/m2 : 0.0 to 6.4 
   13. area - the burned area of the forest (in hectares): 0.00 to 1090.84 

## Objective

Conduct an exploratory analysis with the aim of understanding what factors lead to particularly damaging forest fires.